
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import { Container } from "react-bootstrap";
import Header from "@/component/header";
import '@/css/global.css'
import { Footer } from "@/component/footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hoa tươi Hoàng Vũ",
  description: "Generated by Hoa tươi Hoàng Vũ",
  keywords:'hoa, hoa tươi, hoàng vũ, flower, đà lạt, hoa đà lạt ',
  other:{
    'google-site-verification':'NBGQlDYXMfm6ev4Q6bzCQgv0GNO4Ebxyw8-ALuGWND8'
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
      <meta name="google-site-verification" content="NBGQlDYXMfm6ev4Q6bzCQgv0GNO4Ebxyw8-ALuGWND8" />
      <meta name="google" content="nositelinkssearchbox" key="sitelinks" />
        <meta name="google" content="notranslate" key="notranslate" />
      </Head>
     
      <body className={inter.className}>
        <Header></Header>
        <Container>{children}</Container>
        <Footer></Footer>
        </body>
    </html>
  );
}
