
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import { Container } from "react-bootstrap";
import Header from "@/component/header";
import '@/css/global.css'
import { Footer } from "@/component/footer";
// import "./g/lobals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <Container>{children}</Container>
        <Footer></Footer>
        </body>
    </html>
  );
}
